name: regular export actions

on: 
  schedule: 
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  daily_spotify_playings:
    runs-on: ubuntu-latest
    steps:
      - name: execute daily spotify log
        run: ls

  daily_tweets:
    runs-on: ubuntu-latest
    steps:
      - name: execute daily tweets
        run: ruby daily_tweets_csv_export.rb
